class HDCharger : HDCellWeapon {

    int crankCount;

    default {
        //$Sprite "CGPAA0"

        +hdweapon.fitsinbackpack
        +hdweapon.reverseguninertia
        +inventory.invbar

        scale 0.6;

        inventory.maxamount 1;
        Inventory.icon "CGPAA0";

        weapon.bobrangex 0.22;
        weapon.bobrangey 0.9;

        Tag "$TAG_HANDCHARGE";
        Inventory.PickupMessage "$PICKUP_HANDCHARGE";
        obituary "$OB_HANDCHARGE";

        hdweapon.refid "chg";
        hdweapon.barrelsize 11, 0.3, 0.5;

		hdweapon.loadoutcodes "
			\cumicro - 0/1, whether it accepts Batteries or Micro-Cells
			\cupump - 0/1, whether it cranks or pumps";
    }

    override bool AddSpareWeapon(actor newowner) { return AddSpareWeaponRegular(newowner); }

    override hdweapon GetSpareWeapon(actor newowner, bool reverse, bool doselect) { return GetSpareWeaponRegular(newowner, reverse, doselect); }

    //it was gonna be 70 blocks anyways
    override double weaponbulk() { return 69; }

    override double gunmass() { return 11; }

    override void consolidate() {
        crankCount = 0;
        if (weaponStatus[CHG_BATTERY] > -1) weaponStatus[CHG_BATTERY] = weaponStatus[CHG_BATTYPE] ? 10 : 20;
    }

    override void DrawHUDStuff(HDStatusBar sb, HDWeapon hdw, HDPlayerPawn hpl) {
        int bat = hdw.weaponStatus[CHG_BATTERY];

        sb.drawwepnum(clamp(bat, 0, 5), 5);
        sb.drawwepnum(clamp(bat - 5, 0, 5), 5, posy: -8);
        sb.drawwepnum(clamp(bat - 10, 0, 5), 5, posy: -10);
        sb.drawwepnum(clamp(bat - 15, 0, 5), 5, posy: -12);

        if (hdw.weaponStatus[CHG_BATTERY] > -1) {
            sb.drawnum(
                hdw.weaponStatus[CHG_BATTERY],
                -44, -14,
                sb.DI_SCREEN_CENTER_BOTTOM|sb.DI_TEXT_ALIGN_RIGHT,
                Font.CR_LIGHTBLUE
            );
        }
    }

    // TODO: Localize
    override string gethelptext() {
        return
        WEPHELP_FIRE..(weaponStatus[CHG_FLAGS]&CHG_CRANK?" / "..WEPHELP_ALTFIRE..(weaponStatus[CHG_FLAGS]&CHG_PUMP?" Slide Pump\n":"  Turn Crank\n"):"  \n")
        ..WEPHELP_ALTRELOAD..(weaponStatus[CHG_FLAGS]&CHG_PUMP?
        (weaponStatus[CHG_FLAGS]&CHG_CRANK?"  Release Slide\n":"  Grab Slide\n"):
        (weaponStatus[CHG_FLAGS]&CHG_CRANK?"  Release Crank\n":"  Grab Crank\n"))
        ..(!(weaponStatus[CHG_FLAGS]&CHG_CRANK)?WEPHELP_RELOAD.."  Reload Battery\n":"")
        ..(!(weaponStatus[CHG_FLAGS]&CHG_CRANK)?WEPHELP_UNLOAD.."  Unload Battery\n":"")
        ..WEPHELP_MAGMANAGER
        ;
    }

    override void DrawSightPicture(
        HDStatusBar sb, HDWeapon hdw, HDPlayerPawn hpl,
        bool sightbob, vector2 bob, double fov, bool scopeview, actor hpc, string whichdot
    ) {
        // no-op
    }

    override void DetachFromOwner() {
        Super.DetachFromOwner();

        weaponStatus[CHG_FLAGS] &= ~(CHG_CRANK|CHG_RIGHT|CHG_LEFT);
    }

    // Charging your crystals with a bro
    action void A_CrankinIt() {
        let maxCharge = invoker.weaponStatus[CHG_BATTYPE] ? 10 : 20;
        if (invoker.weaponStatus[CHG_BATTERY] >= 0 && invoker.weaponStatus[CHG_BATTERY] < maxCharge) {
            invoker.crankCount++;

            if (invoker.crankCount >= invoker.weaponStatus[CHG_BATTERY] * 0.25) {
                invoker.crankCount = 0;
                invoker.weaponStatus[CHG_BATTERY]++;
            }
        }

        A_AlertMonsters();
    }

    states {
        Spawn:
            CGPA A -1;
            stop;

        Select0:
            TNT1 A 0 {
                invoker.weaponStatus[CHG_FLAGS] &= ~(CHG_CRANK|CHG_RIGHT|CHG_LEFT);
            }
        Riseup:
            D3UP AA 0 A_raise;
            D3UP AAAAA 0 A_raise;
            CGBL A 1;
            loop;

        Ready:
            CGBL A 1 {
                A_WeaponReady(WRF_ALL);
                A_WeaponBusy(false);
            }
            loop;

        Deselect0:
            TNT1 A 0 A_JumpIf(invoker.weaponStatus[CHG_FLAGS]&CHG_RIGHT, "RightSwitchAway");
            TNT1 A 0 A_JumpIf(invoker.weaponStatus[CHG_FLAGS]&CHG_LEFT, "LeftSwitchAway");
            CGBL A 1 A_lower;
            TNT1 AAA 0 A_lower;
            CGBL A 1 A_lower;
            loop;

        RightSwitchAway:
            TNT1 A 0 {
                invoker.weaponStatus[CHG_FLAGS] &= ~(CHG_CRANK|CHG_RIGHT|CHG_LEFT);
            }
            CGBL G 2;
            CGBL CB 1;
            CGBL A 1 offset(1, 31);
            goto Deselect0;

        LeftSwitchAway:
            TNT1 A 0 {
                invoker.weaponStatus[CHG_FLAGS] &= ~(CHG_CRANK|CHG_RIGHT|CHG_LEFT);
            }
            CGBL LMNG 2;
            CGBL CB 1;
            CGBL A 1 offset(1, 31);
            goto Deselect0;

        Fire:
            TNT1 A 0 A_JumpIf(!(invoker.weaponStatus[CHG_FLAGS]&(CHG_CRANK|CHG_PUMP)), "ready");
            TNT1 A 0 A_JumpIf(invoker.weaponStatus[CHG_FLAGS]&(CHG_PUMP), "PumpCheck");
            goto RightCrankCheck;

        Altfire:
            TNT1 A 0 A_JumpIf(!(invoker.weaponStatus[CHG_FLAGS]&(CHG_CRANK|CHG_PUMP)), "ready");
            TNT1 A 0 A_JumpIf(invoker.weaponStatus[CHG_FLAGS]&(CHG_PUMP), "PumpCheck");
            goto LeftCrankCheck;

        Reload:
            #### # 0 A_JumpIf(invoker.weaponStatus[CHG_BATTERY] >= 0 || !CheckInventory(invoker.weaponStatus[CHG_BATTYPE] ? "HDMicroCell" : "HDBattery", 1), "nope");
            #### A 0 {
                invoker.weaponStatus[CHG_LOADTYPE] = 1;
            }
            Goto Reload1;

        Unload:
            #### # 0 A_JumpIf(invoker.weaponStatus[CHG_BATTERY] < 0, "nope");
            #### A 0 {
                invoker.weaponStatus[CHG_LOADTYPE] = 0;
            }
            Goto Reload1;

        Reload1:
            #### A 4;
            #### B 2 offset(0, 36) A_MuzzleClimb(-frandom(1.2, 2.4), frandom(1.2, 2.4));
            #### C 2 offset(0, 38) A_MuzzleClimb(-frandom(1.2, 2.4), frandom(1.2, 2.4));
            #### C 4 offset(0, 40) {
                A_MuzzleClimb(-frandom(1.2, 2.4), frandom(1.2, 2.4));
                A_StartSound("weapons/bfgclick2", 8);
            }
            #### C 2 offset(0, 42) {
                A_MuzzleClimb(-frandom(1.2, 2.4), frandom(1.2, 2.4));
                A_StartSound("weapons/bfgopen", 8);
                if (invoker.weaponStatus[CHG_BATTERY] >= 0) {
                    let bat = invoker.weaponStatus[CHG_BATTYPE] ? "HDMicroCell" : "HDBattery";
                    if (PressingReload() || PressingUnload()) {
                        HDMagAmmo.GiveMag(self, bat, invoker.weaponStatus[CHG_BATTERY]);
                        A_SetTics(10);
                    } else {
                        HDMagAmmo.SpawnMag(self, bat, invoker.weaponStatus[CHG_BATTERY]);
                        A_SetTics(4);
                    }
                }

                invoker.weaponStatus[CHG_BATTERY] = -1;
            }
            Goto BatteryOut;

        BatteryOut:
            #### C 0 A_JumpIf(!invoker.weaponStatus[CHG_LOADTYPE], "Reload3");
            #### C 4 offset(0, 42) A_StartSound("weapons/pocket", 9);
            #### C 12;
            #### C 12 offset(0, 42) A_StartSound("weapons/bfgbattout", 8);
            #### C 10 offset(0, 36) A_StartSound("weapons/bfgbattpop", 8);
            #### C 0 {
                let battery = HDMagAmmo(FindInventory(invoker.weaponStatus[CHG_BATTYPE] ? "HDMicroCell" : "HDBattery"));	

                if (battery && battery.Amount >= 0) {
                    battery.LowestToLast();
                    invoker.weaponStatus[CHG_BATTERY] = battery.TakeMag(false);
                }
            }
        Reload3:
            #### C 6 offset(0, 38) A_StartSound("weapons/bfgopen", 8);
            #### C 8 offset(0, 37) A_StartSound("weapons/bfgclick2", 8);
            #### C 2 offset(0, 38);
            #### B 2 offset(0, 36);
            #### A 2 offset(0, 34);
            #### A 12;
            Goto Ready;

        Reload4:
            #### CBA 2;
            Goto Nope;

        AltReload:
            TNT1 A 0 A_JumpIf(invoker.weaponStatus[CHG_FLAGS]&CHG_CRANK, "StopThatCrap");
            CGBL A 1 offset(1, 31);
            CGBL A 1 offset(2, 30);
            TNT1 A 0 {
                A_WeaponReady(WRF_NOFIRE|WRF_NOSWITCH);

                if (invoker.weaponStatus[CHG_FLAGS]&CHG_PUMP) {
                    invoker.weaponStatus[CHG_FLAGS] |= CHG_CRANK;
                    A_SetHelpText();

                    SetWeaponState("PumpReload");
                    return;
                }
            }
            CGBL BCDEFGH 2;
            TNT1 A 0 {
                invoker.weaponStatus[CHG_FLAGS] |= CHG_RIGHT|CHG_CRANK;
                A_SetHelpText();
            }
            goto RightCrankWait;

        PumpReload:
            CGPM ABCDEF 2;
            TNT1 A 0 {
                invoker.weaponStatus[CHG_FLAGS] |= CHG_CRANK;
            }
            goto pumpwait;

        //Using the multiplayer-friendly pump-style mode.
        PumpWait:
            // ready to start jerkin' it
            CGPM F 1 A_WeaponReady(WRF_ALLOWUSER1|WRF_NOBOB);
            loop;

        PumpCheck:
            TNT1 A 0 A_StartSound("Oddball/PumpUp", 0);
            TNT1 A 0 offset(1, 29);
            CGPM GH 2 A_JumpIf(!(PressingFire() || PressingAltFire()), "PumpFail");
            CGPM H 1 offset(0, 30);
            CGPM H 0 A_JumpIf(!(PressingFire() || PressingAltFire()), "PumpFail");
            TNT1 A 0 offset(-1, 31);
            TNT1 A 0 {
                A_CrankinIt();
                A_CrankinIt();
                A_CrankinIt();
            }
        //succeed and hold, anything before this ends prematurely
        MidCheck:
            CGPM I 1;
            TNT1 A 0 A_JumpIf(PressingFire() || PressingAltFire(), "MidCheck");
            goto pumpfinish;

        PumpFail:
            CGPM JK 2 offset(-1, 35);
            CGPM K 1 offset(0, 34);
            CGPM F 1 offset(1, 33);
            TNT1 A 0 offset(0, 32);
            goto pumpwait;

        PumpFinish:
            TNT1 A 0 offset(-1, 35);
            TNT1 A 0 {
                A_StartSound("Oddball/PumpDown", 0);
                A_CrankinIt();
            }
            CGPM JK 2 {
                A_CrankinIt();
                A_CrankinIt();
            }
            CGPM K 1 offset(0, 34);
            CGPM F 1 offset(1, 33);
            TNT1 A 0 offset(0, 32);
            goto pumpwait;

        //Waiting while the handle is all the way to the right
        RightCrankWait:
            CGBL H 1 A_WeaponReady(WRF_ALLOWUSER1|WRF_NOBOB);
            loop;

        //If the player fucks up here it means they're actually on the left side
        RightCrankCheck:
            TNT1 A 0 A_JumpIf(invoker.weaponStatus[CHG_FLAGS]&CHG_RIGHT, "RightCrank");
            TNT1 A 0 A_StartSound("OddBall/Woopsie", 0);
            CGBL L 2 offset(1, 31);
            CGBL L 2 offset(-1, 33);
            CGBL L 2 offset(1, 31);
            CGBL L 2 offset(-1, 33);
            CGBL L 2 offset(1, 31);
            CGBL L 2 offset(-1, 33);
            CGBL L 2 offset(1, 31);
            CGBL L 2 offset(-1, 33);
            CGBL L 10;
            goto LeftCrankWait;

        RightCrank:
            TNT1 A 0 offset(1, 29) {
                invoker.weaponStatus[CHG_FLAGS] &= ~CHG_RIGHT;
                invoker.weaponStatus[CHG_FLAGS] |= CHG_LEFT;
                A_StartSound("Oddball/Crank", 0);
            }
            CGBL HI 2 A_CrankinIt();
            TNT1 A 0 offset(0, 30);
            CGBL JK 2 A_CrankinIt();
            TNT1 A 0 offset(-1, 31);
            CGBL LL 2 A_CrankinIt();
            TNT1 A 0 offset(0, 32);
            goto LeftCrankWait;

        //Waiting while the handle is all the way to the left
        LeftCrankWait:
            CGBL L 1 A_WeaponReady(WRF_ALLOWUSER1|WRF_NOBOB);
            Loop;

        //If the player fucks up here it means they're actually on the right side
        LeftCrankCheck:
            TNT1 A 0 A_JumpIf(invoker.weaponStatus[CHG_FLAGS]&CHG_LEFT, "LeftCrank");
            TNT1 A 0 A_StartSound("OddBall/Woopsie", 0);
            CGBL H 2 offset(-1, 33);
            CGBL H 2 offset(1, 31);
            CGBL H 2 offset(-1, 33);
            CGBL H 2 offset(1, 31);
            CGBL H 2 offset(-1, 33);
            CGBL H 2 offset(1, 31);
            CGBL H 2 offset(-1, 33);
            CGBL H 2 offset(1, 31);
            CGBL H 10;
            goto RightCrankWait;
        LeftCrank:
            TNT1 A 0 offset(-1, 35);
            TNT1 A 0 {
                invoker.weaponStatus[CHG_FLAGS] &= ~CHG_LEFT;
                invoker.weaponStatus[CHG_FLAGS] |= CHG_RIGHT;
                A_StartSound("Oddball/Crank", 0);
            }
            CGBL LM 2;
            TNT1 A 0 offset(0, 34);
            CGBL N 1 A_CrankinIt();
            TNT1 A 0 offset(1, 33);
            CGBL G 1;
            TNT1 A 0 offset(1, 33);
            CGBL HH 2;
            TNT1 A 0 offset(0, 32);
            goto RightCrankWait;

        StopThatCrap:
            TNT1 A 0 {
                invoker.weaponStatus[CHG_FLAGS] &= ~(CHG_CRANK|CHG_LEFT);

                A_SetHelpText();

                if (invoker.weaponStatus[CHG_FLAGS]&CHG_PUMP) {
                    SetWeaponState("Pumpstop");
                } else if (invoker.weaponStatus[CHG_FLAGS]&CHG_RIGHT) {
                    SetWeaponState("Rightstop");
                }

                invoker.weaponStatus[CHG_FLAGS] &= ~CHG_RIGHT;
            }
            CGBL LMNG 2;
            goto CrankStop;

        Rightstop:
            CGBL G 2 {
                invoker.weaponStatus[CHG_FLAGS] &= ~CHG_RIGHT;
            }
            goto CrankStop;

        Pumpstop:
            CGPM MNBA 2;
            goto ready;

        CrankStop:
            CGBL FOP 2 {
                invoker.weaponStatus[CHG_FLAGS] &= ~CHG_RIGHT;
            }
            CGBL CB 2;
            CGBL A 1 offset(2, 30);
            CGBL A 1 offset(1, 31);
            TNT1 A 0 A_WeaponReady(WRF_NOFIRE|WRF_NOSWITCH);
            CGBL A 1;
            goto ready;

        user3:
            ---- A 0 A_MagManager(invoker.weaponStatus[CHG_BATTYPE] ? "HDMicroCell" : "HDBattery");
            goto ready;
    }

    override void initializewepstats(bool idfa) {
        weaponStatus[CHG_FLAGS] &= ~(CHG_CRANK|CHG_RIGHT|CHG_LEFT);
        weaponStatus[CHG_BATTERY] = -1;
    }

    override void loadoutconfigure(string input) {

        // Pump vs Crank
        int pump = getloadoutvar(input, "pump", 1);
        if (pump > 0) weaponStatus[CHG_FLAGS] |= CHG_PUMP;

        // Micro-Cells vs Batteries
        int micro = getloadoutvar(input, "micro", 1);
        if (micro > 0) weaponStatus[CHG_BATTYPE] = 1;
    }
}

class ChargerRandom : IdleDummy {
    States {
        Spawn:
            TNT1 A 0 NoDelay {
                let wpn = HDCharger(Spawn("HDCharger", pos, ALLOW_REPLACE));

                if (!wpn) return;

                HDF.TransferSpecials(self, wpn);

                if (!random(0, 2)) wpn.weaponStatus[CHG_FLAGS] |= CHG_PUMP;
                if (!random(0, 2)) wpn.weaponStatus[CHG_BATTYPE] = 1;
            }
            Stop;
    }
}

class BatteryChargerRandom : IdleDummy {
    States {
        Spawn:
            TNT1 A 0 NoDelay {
                let wpn = HDCharger(Spawn("HDCharger", pos, ALLOW_REPLACE));

                if (!wpn) return;

                HDF.TransferSpecials(self, wpn);

                if (!random(0, 2)) wpn.weaponStatus[CHG_FLAGS] |= CHG_PUMP;
            }
            Stop;
    }
}

class MicroCellChargerRandom : IdleDummy {
    States {
        Spawn:
            TNT1 A 0 NoDelay {
                let wpn = HDCharger(Spawn("HDCharger", pos, ALLOW_REPLACE));

                if (!wpn) return;

                HDF.TransferSpecials(self, wpn);

                wpn.weaponStatus[CHG_BATTYPE] = 1;

                if (!random(0, 2)) wpn.weaponStatus[CHG_FLAGS] |= CHG_PUMP;
            }
            Stop;
    }
}

enum oddballstatus {
    CHG_CRANK    = 1,
    CHG_LEFT     = 2,
    CHG_RIGHT    = 4,
    CHG_PUMP     = 8,

    CHG_FLAGS    = 0,
    CHG_BATTERY  = 1,
    CHG_BATTYPE  = 2,
    CHG_LOADTYPE = 3,
    CHG_CHARGE   = 4
};